---
title: "mass"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r}
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))
```

```{r}
Dam_demo_2ndLitters <- Demo_dam %>%
  filter(
    litterNum == 2,
    ParaType == 4,
    is.na(Pups_through_wean) | Pups_through_wean == TRUE,
    !is.na(Dam_Mass_P21)
  )

Dam_demo_2ndLitters
Dam_demo_2ndLitters %>%
  t_test(
  Avg_litter_mass_startPara ~ earlyLifeTrt
)
```

```{r}
Mass_2ndLitters <- Mass_off %>%
  filter(
    litterNum == 2,
    ParaType == 4
  )

Mass_2ndLitters_long <- pivot_longer(
  Mass_2ndLitters,
  cols = starts_with("Mass_P"),
  names_to = "day",
  names_prefix = "Mass_P",
  values_to = "mass",
  values_drop_na = TRUE,
  names_transform = list("day" = as.integer)
) %>%
  relocate(
    day,
    mass,
    .after = earlyLifeTrt
  )
```

## Repeated measured ANOVA, without sex
```{r}
Mass_2ndLitters_long %>%
  filter(
    day != 4 # don't include day 4, start of paradigm
  ) %>%
  anova_test(
    dv = mass,
    wid = mouseID,
    within = day,
    between = earlyLifeTrt,
    type = 3
  )

Mass_2ndLitters_long %>%
  filter(
    day != 4 # don't include day 4, start of paradigm
  ) %>%
  group_by(
    day
  ) %>%
  anova_test(
    dv = mass,
    wid = mouseID,
    between = earlyLifeTrt,
    type = 3
  )%>%
  adjust_pvalue(method = "bonferroni")
```
```{r}
Mass_2ndLitters_long %>%
  filter(
    day != 4 # don't include day 4, start of paradigm
  ) %>%
  anova_test(
    dv = mass,
    wid = mouseID,
    within = day,
    between = c(earlyLifeTrt, sex),
    type = 3
  )

Mass_2ndLitters_long %>%
  filter(
    day != 4 # don't include day 4, start of paradigm
  ) %>%
  group_by(
    day
  ) %>%
  anova_test(
    dv = mass,
    wid = mouseID,
    between = c(earlyLifeTrt, sex),
    type = 3
  )%>%
  adjust_pvalue(method = "bonferroni")
testMulti <- Mass_2ndLitters_long %>%
  filter(
    day != 4 # don't include day 4, start of paradigm
  ) %>%
  group_by(
    sex
  ) %>%
  anova_test(
    dv = mass,
    wid = mouseID,
    within = day,
    between = earlyLifeTrt,
    type = 3
  # )%>%
  # adjust_pvalue(method = "bonferroni"
                )

testMulti$anova
```

Group by dam and sex - no sig diffs with early-life treatment

```{r}
Mass_2ndLitters %>%
  filter(
    damID != "D020-02"
  ) %>%
  getAvgByDam(bySex = TRUE) %>% makeOffMassLong() %>%
  relocate(sex, day, mass, .after = damID) %>%
  filter(
    day != 4
  ) %>%
  anova_test(
    dv = mass,
    wid = damID,
    within = c(day, sex), # now there are multiple sexes for each dam
    between = earlyLifeTrt
  ) %>%
  formatAnova()

Mass_2ndLitters %>%
  filter(
    damID != "D020-02"
  ) %>%
  getAvgByDam(bySex = TRUE) %>% makeOffMassLong() %>%
  filter(
    day != 4
  ) %>%
  group_by(day) %>%
  anova_test(
    dv = mass,
    wid = damID,
    within = c(sex),
    between = earlyLifeTrt
  ) %>%
  formatAnova()
```

Group by dam - interaction between day and early-life treatment, but no sig differences on any given day

```{r}
Mass_2ndLitters %>%
  filter(
    damID != "D020-02"
  ) %>%
  getAvgByDam() %>%
  makeOffMassLong() %>%
  anova_test(
    dv = mass,
    wid = damID, 
    within = day,
    between = earlyLifeTrt
  ) %>%
  formatAnova()

Mass_2ndLitters %>%
  filter(
    damID != "D020-02"
  ) %>%
  getAvgByDam() %>%
  makeOffMassLong() %>%
  group_by(
    day
  ) %>%
  anova_test(
    dv = mass,
    wid = damID,
    between = earlyLifeTrt
  ) %>%
  formatAnova()
```



## Repeated measured ANOVA, with sex
```{r}

```


# Cohort 1

## CBA
```{r}
thisGroupByDam = TRUE
facetBySex = TRUE
useLineType = FALSE
individualLines = TRUE
meanLines = TRUE
zoom_x = FALSE
zoom_x_min = 0
zoom_x_max = 21
zoom_y = FALSE
zoom_y_min = 0
zoom_y_max = 15
indivAlpha = 0.5
meanAlpha = 1
errorBarAlpha = 1
fontSize = 16
STDColor = "#4D4D4D"
LBNColor = "#008B8B"

fileBaseName = "mass_LBN_0001_CBA"
imgType = "png"
thisWidth = 11.5
thisHeight = 5
thisUnits = "in"

df <- Mass_off %>%
  filter(
    cohort == 1,
    damStrain == "CBA"
  )

groupVar <- ifelse(thisGroupByDam, expr(damID), expr(mouseID))

plot <- df %>%
  plot_mass_lines(
    groupByDam = thisGroupByDam,
    facetBySex = facetBySex,
    useLineType = useLineType, # TRUE/FALSE
    lineTypeVar = earlyLifeTrt,
    lineGroupVar = {{ groupVar }},
    xtitle = "PND", #x axis label
    ytitle = "mass (g)", #y axis label
    title = NULL, # plot title
    individualLines = individualLines, # plot individual lines
    meanLines = meanLines, # plot mean lines with SE
    zoom_x = zoom_x, # Zoom to part of x axis
    xmin = zoom_x_min,
    xmax = zoom_x_max,
    zoom_y = zoom_y, # Zoom to part of y axis
    ymin = zoom_y_min,
    ymax = zoom_y_max,
    indivLineAlpha = indivAlpha,
    indivLineSize = 0.8,
    errorBarWidth = 0,
    meanLineSize = 1.4,
    meanAlpha = meanAlpha,
    errorBarSize = 1,
    # errorBarColor = "grey10",
    errorBarAlpha = errorBarAlpha,
    textSize = fontSize,
    axisSize = 0.5,
    legendPosition = "top",
    STDColor = STDColor,
    LBNColor = LBNColor
  )
plot

flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "ephys-2021-12-13"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
```

```{r}

fileBaseName = "mass_LBN_0001_B6"

df <- Mass_off %>%
  filter(
    cohort == 1,
    damStrain == "B6"
  )

groupVar <- ifelse(thisGroupByDam, expr(damID), expr(mouseID))

plot <- df %>%
  plot_mass_lines(
    groupByDam = thisGroupByDam,
    facetBySex = facetBySex,
    useLineType = useLineType, # TRUE/FALSE
    lineTypeVar = earlyLifeTrt,
    lineGroupVar = {{ groupVar }},
    xtitle = "PND", #x axis label
    ytitle = "mass (g)", #y axis label
    title = NULL, # plot title
    individualLines = individualLines, # plot individual lines
    meanLines = meanLines, # plot mean lines with SE
    zoom_x = zoom_x, # Zoom to part of x axis
    xmin = zoom_x_min,
    xmax = zoom_x_max,
    zoom_y = zoom_y, # Zoom to part of y axis
    ymin = zoom_y_min,
    ymax = zoom_y_max,
    indivLineAlpha = indivAlpha,
    indivLineSize = 0.8,
    errorBarWidth = 0,
    meanLineSize = 1.4,
    meanAlpha = meanAlpha,
    errorBarSize = 1,
    # errorBarColor = "grey10",
    errorBarAlpha = errorBarAlpha,
    textSize = fontSize,
    axisSize = 0.5,
    legendPosition = "top",
    STDColor = STDColor,
    LBNColor = LBNColor
  )
plot

flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "ephys-2021-12-13"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
```

```{r}
thisGroupByDam = TRUE
facetBySex = FALSE
useLineType = FALSE
individualLines = TRUE
meanLines = TRUE
zoom_x = FALSE
zoom_x_min = 0
zoom_x_max = 21
zoom_y = FALSE
zoom_y_min = 0
zoom_y_max = 15
indivAlpha = 0.5
meanAlpha = 1
errorBarAlpha = 1
fontSize = 16
STDColor = "#4D4D4D"
LBNColor = "#008B8B"

fileBaseName = "mass_LBN_0001_byStrain"
imgType = "png"
thisWidth = 11.5
thisHeight = 5
thisUnits = "in"

df <- Mass_off %>%
  filter(
    cohort == 1
  )

groupVar <- ifelse(thisGroupByDam, expr(damID), expr(mouseID))

plot <- df %>%
  plot_mass_lines(
    groupByDam = thisGroupByDam,
    facetBySex = facetBySex,
    useLineType = useLineType, # TRUE/FALSE
    lineTypeVar = earlyLifeTrt,
    lineGroupVar = {{ groupVar }},
    xtitle = "PND", #x axis label
    ytitle = "mass (g)", #y axis label
    title = NULL, # plot title
    individualLines = individualLines, # plot individual lines
    meanLines = meanLines, # plot mean lines with SE
    zoom_x = zoom_x, # Zoom to part of x axis
    xmin = zoom_x_min,
    xmax = zoom_x_max,
    zoom_y = zoom_y, # Zoom to part of y axis
    ymin = zoom_y_min,
    ymax = zoom_y_max,
    indivLineAlpha = indivAlpha,
    indivLineSize = 0.8,
    errorBarWidth = 0,
    meanLineSize = 1.4,
    meanAlpha = meanAlpha,
    errorBarSize = 1,
    # errorBarColor = "grey10",
    errorBarAlpha = errorBarAlpha,
    textSize = fontSize,
    axisSize = 0.5,
    legendPosition = "top",
    STDColor = STDColor,
    LBNColor = LBNColor
  ) +
  facet_wrap(
    ~ damStrain
  )
plot

flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "ephys-2021-12-13"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
```


# Cohort 1 vs 2 CBA
```{r}
thisGroupByDam = TRUE
facetBySex = FALSE
useLineType = FALSE
individualLines = TRUE
meanLines = TRUE
zoom_x = FALSE
zoom_x_min = 0
zoom_x_max = 21
zoom_y = FALSE
zoom_y_min = 0
zoom_y_max = 15
indivAlpha = 0.5
meanAlpha = 1
errorBarAlpha = 1
fontSize = 16
STDColor = "#4D4D4D"
LBNColor = "#008B8B"

fileBaseName = "mass_LBN_0001vs2"
imgType = "png"
thisWidth = 11.5
thisHeight = 5
thisUnits = "in"

df <- Mass_off %>%
  filter(
    cohort == 1 | cohort == 2,
    damStrain == "CBA"
  )
df

groupVar <- ifelse(thisGroupByDam, expr(damID), expr(mouseID))

cohort_label <- c(
  "1" = "P2-9",
  "2" = "P4-11"
)

plot <- df %>%
  plot_mass_lines(
    groupByDam = thisGroupByDam,
    facetBySex = facetBySex,
    useLineType = useLineType, # TRUE/FALSE
    lineTypeVar = earlyLifeTrt,
    lineGroupVar = {{ groupVar }},
    xtitle = "PND", #x axis label
    ytitle = "mass (g)", #y axis label
    title = NULL, # plot title
    individualLines = individualLines, # plot individual lines
    meanLines = meanLines, # plot mean lines with SE
    zoom_x = zoom_x, # Zoom to part of x axis
    xmin = zoom_x_min,
    xmax = zoom_x_max,
    zoom_y = zoom_y, # Zoom to part of y axis
    ymin = zoom_y_min,
    ymax = zoom_y_max,
    indivLineAlpha = indivAlpha,
    indivLineSize = 0.8,
    errorBarWidth = 0,
    meanLineSize = 1.4,
    meanAlpha = meanAlpha,
    errorBarSize = 1,
    # errorBarColor = "grey10",
    errorBarAlpha = errorBarAlpha,
    textSize = fontSize,
    axisSize = 0.5,
    legendPosition = "top",
    STDColor = STDColor,
    LBNColor = LBNColor
  ) +
  facet_wrap(
    ~ cohort,
    labeller = labeller(
      cohort = cohort_label
    )
  )
plot

flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "ephys-2021-12-13"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
```