---
title: "Cycles"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r include=FALSE}
# If can't find it, be sure that the directory is the project directory
# Arrow between notebook and settings gear -> Knit directory
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))

```

```{r}
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
```

# Second Litter Females

Cohorts 4 + 6

```{r}
cycles_2ndLitter <- Cycles_off %>%
  filter(
    Litter_num == 2
  )
cyclesLong_2ndLitter <- makeCyclesLong(cycles_2ndLitter)

cycles_2ndLitter_STD_plot <- plotCycleTraces(cyclesLong_2ndLitter %>% filter(earlyLifeTrt == "STD"))
cycles_2ndLitter_LBN_plot <- plotCycleTraces(cyclesLong_2ndLitter %>% filter(earlyLifeTrt == "LBN"))

ggsave(
  filename = paste0(filePrefix, "cycles_2ndLitter_STD.pdf"),
  plot = cycles_2ndLitter_STD_plot,
  device = "pdf",
  path = file.path(plotOutputFolder),
  width = 10,
  height = 7,
  units = "in",
  useDingbats = FALSE
)
ggsave(
  filename = paste0(filePrefix, "cycles_2ndLitter_LBN.pdf"),
  plot = cycles_2ndLitter_LBN_plot,
  device = "pdf",
  path = file.path(plotOutputFolder),
  width = 10,
  height = 7,
  units = "in",
  useDingbats = FALSE
)
```
## Standard-reared
```{r}
cycles_2ndLitter_STD_plot
```

## LBN
```{r}
cycles_2ndLitter_LBN_plot
```

# Percent days in stage
```{r}
cyclesPerc_long_2ndLitter <- makeCyclesPercLong(cycles_2ndLitter)
cyclesPercPlot_2ndLitter <- plotCyclesPercent(cyclesPerc_long_2ndLitter)
cyclesPercPlot_2ndLitter
ggsave(
  filename = paste0(filePrefix, "cycles_2ndLitter_percDaysStage.pdf"),
  plot = cyclesPercPlot_2ndLitter,
  device = "pdf",
  path = file.path(plotOutputFolder),
  width = 5,
  height = 5,
  units = "in",
  useDingbats = FALSE
)
```

# Cycles distribution
```{r}
cycles_2ndLitter_contTable <- table(
  cyclesLong_2ndLitter$earlyLifeTrt,
  cyclesLong_2ndLitter$stageName
)

cycles_2ndLitter_ChiSq <- chisq_test(cycles_2ndLitter_contTable)
cycles_2ndLitter_ChiSq %>% flextable()

chisq_descriptives(cycles_2ndLitter_ChiSq) %>% flextable()
```

```{r}
cycles_2ndLitter %>%
t_test(Proestrus_days ~ earlyLifeTrt)
```
# Cycle Pics in PPT

## Cohort 4
```{r}
LBN_0004_CyclingFolder <- "/Volumes/Shared3/Physiology-Moenter_Lab/gibsonag/LBN/LBN_0004/Cycles"
LBN_0004_Folders <- Cycles_off %>%
  filter(
    Cohort == 4
  ) %>%
  arrange(
    earlyLifeTrt,
    DOB
  ) %>%
  select(
    FolderName
  )
LBN_0004_cyclePPT <- read_pptx("./estrousCycleTemplate.pptx")
LBN_0004_cyclePPT <- ph_with(LBN_0004_cyclePPT, "LBN_0004 Female Cycle Pictures: P70-90", location = ph_location_type("title"))
```

```{r}
for(mouse in LBN_0004_Folders$FolderName){
  LBN_0004_cyclePPT <- addMouseFolderImgsTocyclePPT(
    mouse,
    LBN_0004_CyclingFolder,
    LBN_0004_cyclePPT,
    numPerSlide = 12
  )
}
```

```{r}
print(LBN_0004_cyclePPT, file.path(reportOutputFolder, "cyclePPTS", "LBN_0004_cycleImgs_P70-90.pptx"))
```



