---
title: "LBN Female Use"
output:
  word_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r include=FALSE}
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))
source("./01-scripts/04-filter-datasets.R")
# source("./01-scripts/05-make-LBN-plots.R")
# source("./01-scripts/06-make-LBN-ANOVAs.R")
```

```{r}
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
```

```{r}
addLocation <- function(df){
  movedCohorts <- c(1:6)
  df <- df %>%
    mutate(
      moved = ifelse(cohort %in% movedCohorts, TRUE, FALSE)
      , .after = cohort
    )
  return(df)
}
```


```{r}
LBN_females <- LBN_all %>%
  filterLBNCohorts() %>%
  filter(
    sex == "F"
  ) %>%
  select(
    mouseID,
    damID,
    sex,
    cohort,
    litterNum,
    earlyLifeTrt,
    adultTrt,
    Sac_cycle,
    ReproTract_mass,
    Sac_hr,
    Sac_stop_off
    # , starts_with("LH_hr")
  ) %>%
  addLocation() %>%
  filter(
    is.na(Sac_stop_off)
  ) %>%
  select(
    -Sac_stop_off
  )

femaleUse <- LBN_females %>%
  mutate(
    adultDi = ifelse(
      !is.na(Sac_cycle),
      ifelse(Sac_cycle == "diestrus", TRUE, FALSE),
      NA
    ),
    adultProLH = ifelse(
      !is.na(Sac_cycle),
      ifelse(Sac_cycle == "proestrus" & is.na(Sac_hr), TRUE, FALSE),
      NA
    ),
    adultProEphys = ifelse(
      !is.na(Sac_cycle),
      ifelse(Sac_cycle == "proestrus" & !is.na(Sac_hr), TRUE, FALSE),
      NA
    ),
    hitCycle = ifelse(
      !is.na(Sac_cycle),
      ifelse(
        (Sac_cycle == "proestrus" & ReproTract_mass >= proUterineMin) |
        (Sac_cycle == "diestrus" & ReproTract_mass <= diUterineMax),
        TRUE,
        FALSE
      ),
      NA
    ),
    otherUse = ifelse(
      !is.na(Sac_hr) & is.na(Sac_cycle),
      TRUE,
      NA
    )
  ) %>%
  arrange(
    -adultDi,
    -adultProLH,
    -adultProEphys,
    -hitCycle,
    -otherUse,
    earlyLifeTrt,
    adultTrt,
    litterNum,
    mouseID
  )

diFemalesUse <- femaleUse %>%
  filter(
    adultDi == TRUE & hitCycle == TRUE
  ) %>%
  group_by(
    earlyLifeTrt,
    adultTrt,
    litterNum,
    moved
  ) %>%
  summarize(
    count = n()
    , .groups = "drop"
  )

proLHFemalesUse <- femaleUse %>%
  filter(
    adultProLH == TRUE & hitCycle == TRUE
  ) %>%
  group_by(
    earlyLifeTrt,
    adultTrt,
    litterNum
    , moved
  ) %>%
  summarize(
    count = n()
    , .groups = "drop"
  )

proEphysFemalesUse <- femaleUse %>%
  filter(
    adultProEphys == TRUE & hitCycle == TRUE
  ) %>%
  group_by(
    earlyLifeTrt,
    adultTrt,
    litterNum
    , moved
  ) %>%
  summarize(
    count = n()
    , .groups = "drop"
  )

```

```{r}
addRecDaysFunc <- function(df){
  df <- df %>%
    mutate(
      recDays = ifelse(
        ((cohort == 7 | cohort == 8 | damID == "D015") & damID != "D051-01")
        , "P4-6"
        , ifelse(
          (cohort == 2 | cohort == 4 | cohort == 6 | damID == "D051-01")
          , "P5-6"
          , ifelse(
            cohort == 9 | cohort == 10
            , "P4-11"
            , NA
          )
        )
      )
    )
  return(df)
}
```

```{r}
numFemalesInLitter <- Demo_off %>%
  filterLBNCohorts() %>%
  filter(
    sex == "F"
  ) %>%
  group_by(
    damID
  ) %>%
  summarize(
    numFemales = n()
    , .groups = "drop"
  )

numFemalesInLitter

damInfo <- damFiltered %>%
  left_join(
    numFemalesInLitter
    , by = "damID"
  ) %>%
  addLocation() %>%
  addRecDaysFunc() %>%
  select(
    damID
    , cohort
    , litterNum
    , moved
    , recDays
    , earlyLifeTrt
    , Litter_size
    , numFemales
  ) %>%
  arrange(
    cohort
    , earlyLifeTrt
  )

damInfo
```

```{r}
sumDamInfo <- damInfo %>%
  group_by(
    earlyLifeTrt
    , litterNum
    , moved
    , recDays
  ) %>%
  summarize(
    numLitters = n()
    , .groups = "drop"
  )
```


```{r}
sumGabaInfo <- GABApscsFilteredFiring %>%
  addLocation() %>%
  countMiceAndLitters(
    groupingVars = vars(earlyLifeTrt, adultTrt, litterNum, moved)
  )
sumGabaInfo


GABApscsFilteredFiring %>%
  group_by(mouseID) %>%
  summarize(
    uterineMass = ReproTract_mass
  )
```

## Count unused and available
```{r}
cohort9_available <- LBN_data %>%
  filter(
    cohort == 9 | cohort == 10
    , is.na(Pups_through_wean) | Pups_through_wean == TRUE
    , sex == "F"
    , is.na(Sac_date)
    , is.na(Sac_stop_off)
    , mouseID != 918 # screwed up and forgot to add scent
  ) %>%
  group_by(
    earlyLifeTrt
  ) %>%
  summarize(
    n = n()
    , .groups = "drop"
  )
cohort9_available

LBN_data %>%
  filter(
    cohort == 9 | cohort == 10
    , is.na(Pups_through_wean) | Pups_through_wean == TRUE
    , sex == "F"
    , is.na(Sac_date)
    , is.na(Sac_stop_off)
    , mouseID != 918 # screwed up and forgot to add scent
  ) %>%
  arrange(
    mouseID
  )
```

# Males 

```{r}
malesUsed <- acuteStressFilteredMales %>%
  filter(
    cohort %in% c(7, 9, 10)
  ) %>%
  group_by(
    earlyLifeTrt
    , adultTrt
  ) %>%
  summarize(
    n()
    , numLitters = length(unique(damID))
  )

malesUsed
```

```{r}
maleCortAdmin <- loadExcelSheet(dataFolder, LBN_DataName, "cortAdmin") %>%
  makeFactors(
    c(
      mouseID
      , adultTrt
      , dosage
    )
  )

cortAdminMales <- maleCortAdmin$mouseID
```

```{r}
cohort9_males_available <- LBN_data %>%
  filter(
    cohort == 9
    , is.na(Pups_through_wean) | Pups_through_wean == TRUE
    , sex == "M"
    , is.na(Sac_date)
    , is.na(numInCage) | numInCage > 1
    , !(mouseID %in% cortAdminMales)
  ) %>%
  group_by(
    earlyLifeTrt
  ) %>%
  summarize(
    n = n()
    , .groups = "drop"
  )
cohort9_males_available 
```



```{r}

saveUseInfoDFsToExcel(
  "animalInfo",
  "damInfo" = damInfo,
  "damCounts" = sumDamInfo,
  "femaleUse" = femaleUse,
  "diestrus" = diFemalesUse,
  "proLH" = proLHFemalesUse,
  "proEphys" = proEphysFemalesUse
  , "GABApscs" = sumGabaInfo
  , "female_avail" = cohort9_available
  , "maleUsed" = malesUsed
  , "male_avail" = cohort9_males_available
)

saveDFsToExcel(
  "animalInfo_noColor",
  "damInfo" = damInfo,
  "damCounts" = sumDamInfo,
  "femaleUse" = femaleUse,
  "diestrus" = diFemalesUse,
  "proLH" = proLHFemalesUse,
  "proEphys" = proEphysFemalesUse
  , "GABApscs" = sumGabaInfo
  , "female_avail" = cohort9_available
  , "maleUsed" = malesUsed
  , "male_avail" = cohort9_males_available
)
```





