---
title: "Plotting with LMM"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# knitr::opts_chunk$set(fig.width=11.5, fig.height=5) 
# options(digits=3)
```

```{r include=FALSE}
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))
source("./01-scripts/04-filter-datasets.R")
source("./01-scripts/05-make-LBN-plots-manuscript.R")
source("./01-scripts/06-make-LBN-ANOVAs_noLitter.R")
```

```{r}
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
```

# Fit the mixed model

```{r}
lmm <- mixed(
  VO_age ~ earlyLifeTrt + (1|damID)
  , data = maturationFiltered
  , method = "KR"
)

lmm
```

## Checking assumptions

```{r}
plot(lmm$full_model)
```

```{r}
qqnorm(residuals(lmm$full_model))
```



# Get the error information for the model

## Model based

```{r}
lmmData_model <- lmm %>%
  getErrorDF_LMM("earlyLifeTrt")

lmmData_model
```


## Mean/SEM of each group

```{r}
lmmData_means <- lmm %>%
  getErrorDF_LMM("earlyLifeTrt", "mean")

lmmData_means
```


# Plot with error


```{r}
basePlot <- maturation_byDam_f %>%
  scatterPlotLBN(
    yVar = VO_age
    , yLab = "mean age at VO (days)"
  )

basePlot
```

## Model based

```{r}
basePlot +
  plotError_LMM(
    lmmData_model
    , earlyLifeTrt
  )
```
## Mean based

These are the same error bars as plotted by ggplot from the data

```{r}
basePlot +
  plotError_LMM(
    lmmData_means
    , earlyLifeTrt
  )
```



