---
title: "Cycles"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r include=FALSE}
# If can't find it, be sure that the directory is the project directory
# Arrow between notebook and settings gear -> Knit directory
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))

```

```{r}
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
```

# Second Litter Females

Cohorts 4 + 6

```{r}
cycles_2ndLitter <- Cycles_off %>%
  filter(
    litterNum == 2,
    Litter_size >= 5 # added 2022-01-17
  )
cyclesLong_2ndLitter <- makeCyclesLong(cycles_2ndLitter)

cycles_2ndLitter_STD_plot <- plotCycleTraces(cyclesLong_2ndLitter %>% filter(earlyLifeTrt == "STD"))
cycles_2ndLitter_LBN_plot <- plotCycleTraces(cyclesLong_2ndLitter %>% filter(earlyLifeTrt == "LBN"))

flexSave(
  "cycles_2ndLitter_STD",
  plot = cycles_2ndLitter_STD_plot,
  width = 11,
  height = 8.5,
  units = "in",
  fileType = "png"
)
# ggsave(
#   filename = paste0(filePrefix, "cycles_2ndLitter_STD.pdf"),
#   plot = cycles_2ndLitter_STD_plot,
#   device = "pdf",
#   path = file.path(plotOutputFolder),
#   width = 10,
#   height = 7,
#   units = "in",
#   useDingbats = FALSE
# )
flexSave(
  "cycles_2ndLitter_LBN",
  plot = cycles_2ndLitter_LBN_plot,
  width = 11,
  height = 8.5,
  units = "in",
  fileType = "png"
)
# ggsave(
#   filename = paste0(filePrefix, "cycles_2ndLitter_LBN.pdf"),
#   plot = cycles_2ndLitter_LBN_plot,
#   device = "pdf",
#   path = file.path(plotOutputFolder),
#   width = 10,
#   height = 7,
#   units = "in",
#   useDingbats = FALSE
# )

```
## Standard-reared
```{r}
cycles_2ndLitter_STD_plot
```

## LBN
```{r}
cycles_2ndLitter_LBN_plot
```

# Percent days in stage
```{r}
cyclesPerc_long_2ndLitter <- makeCyclesPercLong(cycles_2ndLitter)
cyclesPercPlot_2ndLitter <- plotCyclesPercent(cyclesPerc_long_2ndLitter, fontSize = 16, dotSize = 2.5)
cyclesPercPlot_2ndLitter
flexSave(
  "cycles_2ndLitter_percDaysStage",
  plot = cyclesPercPlot_2ndLitter,
  width = 5,
  height = 5,
  units = "in"
)
flexSave(
  "cycles_2ndLitter_percDaysStage",
  plot = cyclesPercPlot_2ndLitter,
  width = 4.65,
  height = 4.62,
  units = "in",
  fileType = "png"
)
# ggsave(
#   filename = paste0(filePrefix, "cycles_2ndLitter_percDaysStage.pdf"),
#   plot = cyclesPercPlot_2ndLitter,
#   device = "pdf",
#   path = file.path(plotOutputFolder),
#   width = 5,
#   height = 5,
#   units = "in",
#   useDingbats = FALSE
# )
```

# Cycles distribution
```{r}
cycles_2ndLitter_contTable <- table(
  cyclesLong_2ndLitter$earlyLifeTrt,
  cyclesLong_2ndLitter$stageName
)

cycles_2ndLitter_ChiSq <- chisq_test(cycles_2ndLitter_contTable)
cycles_2ndLitter_ChiSq %>% flextable()

chisq_descriptives(cycles_2ndLitter_ChiSq) %>% flextable()
```

```{r}
cycles_2ndLitter %>%
t_test(Proestrus_days ~ earlyLifeTrt)
```
# Cycle Pics in PPT

## Cohort 4
```{r}
LBN_0004_CyclingFolder <- CohortCyclingFolder$cyclingFolderPath[CohortCyclingFolder$cohort == 4]

LBN_0004_Folders <- Cycles_off %>%
  filter(
    cohort == 4
  ) %>%
  arrange(
    earlyLifeTrt,
    DOB
  ) %>%
  select(
    FolderName
  )
LBN_0004_cyclePPT <- read_pptx("./estrousCycleTemplate.pptx")
LBN_0004_cyclePPT <- ph_with(
  LBN_0004_cyclePPT, 
  "LBN_0004 Female Cycle Pictures: P70-90", 
  location = ph_location_label("Title 1"))
```

```{r}
for(mouse in LBN_0004_Folders$FolderName){
  LBN_0004_cyclePPT <- addMouseFolderImgsTocyclePPT(
    mouse,
    LBN_0004_CyclingFolder,
    LBN_0004_cyclePPT,
    numPerSlide = 12
  )
}
```

```{r}
print(LBN_0004_cyclePPT, file.path(reportOutputFolder, "cyclePPTS", "LBN_0004_cycleImgs_P70-90.pptx"))
```

## Cohort 5
```{r}
LBN_0005_CyclingFolder <- CohortCyclingFolder$cyclingFolderPath[CohortCyclingFolder$cohort == 5]

LBN_0005_Folders <- Cycles_off %>%
  filter(
    cohort == 5
  ) %>%
  arrange(
    earlyLifeTrt,
    DOB
  ) %>%
  select(
    FolderName
  )
LBN_0005_cyclePPT <- read_pptx("./estrousCycleTemplate.pptx")
LBN_0005_cyclePPT <- ph_with(
  LBN_0005_cyclePPT, 
  "LBN_0005 Female Cycle Pictures", 
  location = ph_location_label("Title 1")
  )
```

```{r}
for(mouse in LBN_0005_Folders$FolderName){
  LBN_0005_cyclePPT <- addMouseFolderImgsTocyclePPT(
    mouse,
    LBN_0005_CyclingFolder,
    LBN_0005_cyclePPT,
    numPerSlide = 12
  )
}
```

```{r}
print(LBN_0005_cyclePPT, file.path(reportOutputFolder, "cyclePPTS", "LBN_0005_cycleImgs.pptx"))
```


# 2021-10-19 - For SFN Poster
```{r}
cycles_2ndLitter <- Cycles_off %>%
  filter(
    litterNum == 2,
    Litter_size>=5
  )

STDMice <- cycles_2ndLitter %>%
  filter(
    earlyLifeTrt == "STD"
  )
STDtoUse <- STDMice[sample(nrow(STDMice))[1:16], ] %>% makeCyclesLong()

LBNMice <- cycles_2ndLitter %>%
  filter(
    earlyLifeTrt == "LBN"
  )
LBNtoUse <- LBNMice[sample(nrow(LBNMice))[1:16], ] %>% makeCyclesLong()

# cycles_2ndLitter_STD_plot <- plotCycleTraces(cyclesLong_2ndLitter %>% filter(earlyLifeTrt == "STD"), 
#                                              removeFacets = TRUE)
# cycles_2ndLitter_LBN_plot <- plotCycleTraces(cyclesLong_2ndLitter %>% filter(earlyLifeTrt == "LBN"),
#                                              removeFacets = TRUE)

cycles_2ndLitter_STD_plot <- plotCycleTraces(STDtoUse, 
                                             colorValues = c("grey30", "cyan4"),
                                             fontSize = 16,
                                             removeFacets = TRUE
                                             ) + theme(
                                               axis.text.x = element_text(size = 10)
                                             )
cycles_2ndLitter_LBN_plot <- plotCycleTraces(LBNtoUse,
                                             colorValues = c("grey30", "cyan4"),
                                             fontSize = 16,
                                             removeFacets = TRUE
                                             )+ theme(
                                               axis.text.x = element_text(size = 10)
                                             )

cycles_2ndLitter_STD_plot
cycles_2ndLitter_LBN_plot

flexSave(
  "cycles_2ndLitter_STD",
  plot = cycles_2ndLitter_STD_plot,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = 4,
  height = 5.5,
  units = "in",
  fileType = "png"
)

flexSave(
  "cycles_2ndLitter_LBN",
  plot = cycles_2ndLitter_LBN_plot,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = 4,
  height = 5.5,
  units = "in",
  fileType = "png"
)
```

```{r}
cycles_demo <- Cycles_off %>%
  filter(
    mouseID == 422
  )
cyclesLong_demo <- makeCyclesLong(cycles_demo) %>% filter(
  day < 22
)

plot <- plotCycleTraces(cyclesLong_demo, removeFacets = TRUE, fontSize = 16)

plot

imgType = "png"
thisWidth = 11
thisHeight = 5.5
thisUnits = "in"

fileBaseName = "Demo_cyclesPlot"

flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
```

