---
title: "Effect of LBN on offspring maturation"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '4'
  html_notebook:
    toc: yes
    toc_depth: 4
  word_document:
    toc: yes
    toc_depth: '4'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r include=FALSE}
# If can't find it, be sure that the directory is the project directory
# Arrow between notebook and settings gear -> Knit directory
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))

```

```{r}
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
```

# By Dam
The paradigm was run with dams' first or second litters

```{r}
filteredDF <- Maturation_off %>%
  filter(
    damStrain == "CBA",
    cohort == 2 | cohort == 4 | cohort == 6 | cohort == 7 | cohort == 8,
    Litter_size >= 5
  )
Maturation_byDam_5plusPups_females <- filteredDF %>%
  filter(
    sex == "F"
  ) %>%
  getAvgByDam()
Maturation_byDam_5plusPups_males <- filteredDF %>%
  filter(
    sex == "M"
  ) %>%
  getAvgByDam()

df_females <- Maturation_byDam_5plusPups_females
df_males <- Maturation_byDam_5plusPups_males
```
## Maturation

### Vaginal Opening
#### Age
```{r}
df_females %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(VO_age)%>%
  myDisplay()
t_test(
  df_females %>% filter(!is.na(VO_age)),
  VO_age ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()

max_VO_age <- df_females$VO_age %>% max(na.rm = TRUE)
```
#### Mass
```{r}
df_females %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(VO_mass)%>%
  myDisplay()
t_test(
  df_females %>% filter(!is.na(VO_mass)),
  VO_mass ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
max_VO_mass <- df_females$VO_mass %>% max(na.rm = TRUE)
```

```{r}
VO_age_plot <- df_females %>%
  scatterPlotLBN(yVar = VO_age, "age at VO (days)", textSize = 16, dotSize = 3)
VO_mass_plot <- df_females %>%
  scatterPlotLBN(yVar = VO_mass, "mass at VO (g)", textSize = 16, dotSize = 3)
```

### First Estrus
#### Age
```{r}
df_females %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(Estrus_age) %>%
  myDisplay()
t_test(
  df_females %>% filter(!is.na(Estrus_age)),
  Estrus_age ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
max_estrus_age <- df_females$Estrus_age %>% max(na.rm = TRUE)
```
#### Mass
```{r}
df_females %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(Estrus_mass)%>%
  myDisplay()
t_test(
  df_females %>% filter(!is.na(Estrus_mass)),
  Estrus_mass ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
max_estrus_mass <- df_females$Estrus_mass %>% max(na.rm = TRUE)
```

```{r}
Estrus_age_plot <- df_females %>%
  scatterPlotLBN(yVar = Estrus_age, "age at first estrus (days)", textSize = 16, dotSize = 3)
Estrus_mass_plot <- df_females %>%
  scatterPlotLBN(yVar = Estrus_mass, "mass at first estrus (g)", textSize = 16, dotSize = 3)
```

### Preputial Separation
#### Age
```{r}
df_males %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(PreputialSep_age)%>%
  myDisplay()
t_test(
  df_males %>% filter(!is.na(PreputialSep_age)),
  PreputialSep_age ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
max_PPS_age <- df_males$PreputialSep_age %>% max(na.rm = TRUE)
```
#### Mass
```{r}
df_males %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(PreputialSep_mass)%>%
  myDisplay()
t_test(
  df_males %>% filter(!is.na(PreputialSep_mass)),
  PreputialSep_mass ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
max_PPS_mass <- df_males$PreputialSep_mass %>% max(na.rm = TRUE)
```

```{r}
PreputialSep_age_plot <- df_males %>%
  scatterPlotLBN(yVar = PreputialSep_age, "age at preputial sep. (days)", textSize = 16, dotSize = 3)
PreputialSep_mass_plot <- df_males %>%
  scatterPlotLBN(yVar = PreputialSep_mass, "mass at preputial sep. (g)", textSize = 16, dotSize = 3)
```

```{r}
litterNum_label <- c(
  "1" = "first litter",
  "2" = "second litter"
)

facetForLitterNum <- facet_grid(
    cols = vars(litterNum),
    labeller = labeller(
      litterNum = litterNum_label
    )
  )

imgType = "png"
thisWidth = 4
thisHeight = 5.5
thisUnits = "in"


```


### Age Plots
```{r}
max_age <- max(max_VO_age, max_estrus_age, max_PPS_age, na.rm = TRUE) + 3
agePlots <- plot_grid(
  VO_age_plot + expand_limits(y = max_age) + facetForLitterNum + labs(title = "vaginal opening"),
  Estrus_age_plot + expand_limits(y = max_age) + facetForLitterNum + labs(title = "first estrus"),
  PreputialSep_age_plot + expand_limits(y = max_age) + facetForLitterNum + labs(title = "preputial separation"),
  nrow = 1,
  align = "hv"
)

fileBaseName = "VO_age_litterNum"
plot = VO_age_plot + expand_limits(y = max_age) + facetForLitterNum
flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
fileBaseName = "estrus_age_litterNum"
plot = Estrus_age_plot + expand_limits(y = max_age) + facetForLitterNum
flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
fileBaseName = "pps_age_litterNum"
plot = PreputialSep_age_plot + expand_limits(y = max_age) + facetForLitterNum
flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
```

### Mass Plots
```{r}
max_mass <- max(max_VO_mass, max_estrus_mass, max_PPS_mass, na.rm = TRUE) + 3
massPlots <- plot_grid(
  VO_mass_plot + expand_limits(y = max_mass) + facetForLitterNum,
  Estrus_mass_plot + expand_limits(y = max_mass) + facetForLitterNum,
  PreputialSep_mass_plot + expand_limits(y = max_mass) + facetForLitterNum,
  nrow = 1,
  align = "hv"
)

fileBaseName = "VO_mass_litterNum"
plot = VO_mass_plot + expand_limits(y = max_mass) + facetForLitterNum
flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
fileBaseName = "estrus_mass_litterNum"
plot = Estrus_mass_plot + expand_limits(y = max_mass) + facetForLitterNum
flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
fileBaseName = "pps_mass_litterNum"
plot = PreputialSep_mass_plot + expand_limits(y = max_mass) + facetForLitterNum
flexSave(
  baseName = fileBaseName,
  thisFilePrefix = NULL,
  plot = plot,
  fileType = imgType,
  filePath = file.path(plotOutputFolder, "NGP"),
  width = thisWidth,
  height = thisHeight,
  units = thisUnits,
  compType = currentCompType,
  shinySettings = FALSE
)
```

## AGD

### Females


#### Summary
##### Adult AGD
```{r}
df_females %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(AGD_adult)%>%
  myDisplay()
t_test(
  df_females %>% filter(!is.na(AGD_adult)),
  AGD_adult ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
```

##### Adult Mass
```{r}
df_females %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(Mass_adult)%>%
  myDisplay()
t_test(
  df_females %>% filter(!is.na(Mass_adult)),
  Mass_adult ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
```

#### Plots
```{r}
AGD_plot_females <- df_females %>%
  scatterPlotLBN(
    AGD_adult,
    "anogenital distance (mm)"
  )
AdMass_plot_females <- df_females %>%
  scatterPlotLBN(
    Mass_adult,
    "body mass (g)"
  )
plot_grid(
  AGD_plot_females,
  AdMass_plot_females,
  align = c("hv")
)
```
```{r eval=FALSE, include=FALSE}
# Correlation between agd and mass
df_females %>%
  scatterPlotTwoVars_byLBN(
    yVar = AGD_adult,
    yLab = "anogenital distance (mm)",
    xVar = Mass_adult,
    xLab = "body mass (g)"
  )
```

### Males
#### Summary
##### Adult AGD
```{r}
df_males %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(AGD_adult)%>%
  myDisplay()
t_test(
  df_males %>% filter(!is.na(AGD_adult)),
  AGD_adult ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
```

##### Adult Mass
```{r}
df_males %>%
  group_by(earlyLifeTrt) %>%
  meanSummary(Mass_adult)%>%
  myDisplay()
t_test(
  df_males %>% filter(!is.na(Mass_adult)),
  Mass_adult ~ earlyLifeTrt,
  p.adjust.method = "bonferroni"
)%>%
  myDisplay()
```

#### Plots
```{r}
AGD_plot_males <- df_males %>%
  scatterPlotLBN(
    AGD_adult,
    "anogenital distance (mm)"
  )
AdMass_plot_males <- df_males %>%
  scatterPlotLBN(
    Mass_adult,
    "body mass (g)"
  )
plot_grid(
  AGD_plot_males,
  AdMass_plot_males,
  align = c("hv")
)
```


```{r}
df_females %>%
  anova_test(
    dv = VO_age,
    between = c(litterNum, earlyLifeTrt)
  )
df_females %>%
  anova_test(
    dv = Estrus_age,
    between = c(litterNum, earlyLifeTrt)
  )
df_males %>%
  anova_test(
    dv = PreputialSep_age,
    between = c(litterNum, earlyLifeTrt)
  )
df_females %>%
  anova_test(
    dv = VO_mass,
    between = c(litterNum, earlyLifeTrt)
  )
df_females %>%
  anova_test(
    dv = Estrus_mass,
    between = c(litterNum, earlyLifeTrt)
  )
df_males %>%
  anova_test(
    dv = PreputialSep_mass,
    between = c(litterNum, earlyLifeTrt)
  )
```

