---
title: "Nutella - Cort Admin"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r include=FALSE}
# If can't find it, be sure that the directory is the project directory
# Arrow between notebook and settings gear -> Knit directory
source("./01-scripts/01-set-up.R") ## IDK why, but doesn't seem to work the first time in new environment
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "cortAdmin-get-datasets.R"))
```

```{r}
BD_offspringInfo %>%
  filter(
    cohort == "AG_BW"
  ) %>%
  createRemainingPPT(
    addToName = "BD" 
    , includeYesterday = TRUE
    , useVar = Sampling_date
    )
```

```{r}
BD_offspringInfo %>%
  filter(
    cohort == "AG_BW"
  ) %>%
  createOvulationPPT(
    addToName = "BD"
    , cyclesDF = BD_cycles
    , useVar = Sampling_date
    , sortByCycle = FALSE
    , sortByLH = FALSE
    , sortByDate = TRUE
    )
```

```{r}
saveDFsToExcel(
  "nutellaCortAdmin"
  , prefix = ""
  , "cortAdmin" = BD_sampling %>%
    select(
      mouseID,
      dosage,
      oocytes1,
      oocytes2,
      notes,
      Sac_stage,
      Uterine_description,
      trust,
      starts_with("LH"),
      maxLH,
      timeAtMax
    ) %>%
    arrange(
      -trust,
      dosage,
      maxLH
    )
)

```
```{r}
cortAdminLH_trust <- LHPlot_adultTrt(
  BD_LH %>% makeFactors(dosage) %>% filter(trust == TRUE, !is.na(LH)),
  trtVar = dosage,
  trtName = "doseage (mg/kg)",
  trtLineGuide = c("0" = "dotted", "2" = "solid"),
  trtFill = scale_fill_manual(
    "dosage (mg/kg)",
    values = c("0" = "white", "2" = "black")
  ),
  trtColor = scale_color_manual(
    "dosage (mg/kg)",
    values = c("0" = "black", "2" = "black")
  ),
  fontSize = 16
  , dotSize = 2.5
  , zoom_y = TRUE
  , ymin = 0
  , ymax = 45
) + facet_wrap(
  ~ dosage,
  ncol = 2
)

cortAdminLH_dontTrust <- LHPlot_adultTrt(
  BD_LH %>% makeFactors(dosage) %>% filter(trust == FALSE, !is.na(LH)),
  trtVar = dosage,
  trtName = "doseage (mg/kg)",
  trtLineGuide = c("0" = "dotted", "2" = "solid"),
  trtFill = scale_fill_manual(
    "dosage (mg/kg)",
    values = c("0" = "white", "2" = "black")
  ),
  trtColor = scale_color_manual(
    "dosage (mg/kg)",
    values = c("0" = "black", "2" = "black")
  ),
  fontSize = 16
  , dotSize = 2.5
  , zoom_y = TRUE
  , ymin = 0
  , ymax = 45
) + facet_wrap(
  ~ dosage,
  ncol = 2
)

cortAdminLH_unsure <- LHPlot_adultTrt(
  BD_LH %>% makeFactors(dosage) %>% filter(is.na(trust), !is.na(LH)),
  trtVar = dosage,
  trtName = "doseage (mg/kg)",
  trtLineGuide = c("0" = "dotted", "2" = "solid"),
  trtFill = scale_fill_manual(
    "dosage (mg/kg)",
    values = c("0" = "white", "2" = "black")
  ),
  trtColor = scale_color_manual(
    "dosage (mg/kg)",
    values = c("0" = "black", "2" = "black")
  ),
  fontSize = 16
  , dotSize = 2.5
  , zoom_y = TRUE
  , ymin = 0
  , ymax = 45
) + facet_wrap(
  ~ dosage,
  ncol = 2
)

cortAdminLH_trust
cortAdminLH_dontTrust
# cortAdminLH_unsure
```
```{r}
flexSave(
  "LH_trust",
  "cortAdmin",
  cortAdminLH_trust,
  "png",
  width = 11,
  height = 5.5
)
flexSave(
  "LH_dontTrust",
  "cortAdmin",
  cortAdminLH_dontTrust,
  "png",
  width = 11,
  height = 5.5
)
flexSave(
  "LH_unsure",
  "cortAdmin",
  cortAdminLH_unsure,
  "png",
  width = 11,
  height = 5.5
)
```

```{r}
BD_ovulation <- BD_sampling %>%
  filter(
    cohort == "AG_BW",
    trust == TRUE
  ) %>%
  mutate(
    ovulated = ifelse(oocytes1>0 | oocytes2 > 0, TRUE, FALSE),
    numOocytes = oocytes1 + oocytes2,
    .after = oocytes2
  )

BD_ovulation%>%
  group_by(dosage, ovulated) %>%
  summarize(
    n = n()
  )

BD_ovulation_plot <- BD_ovulation %>%
  propOvulatedPlot(
    xVar = dosage,
    fontSize = 16
  )

BD_ovulation_plot 

BD_oocytes_plot <- BD_ovulation %>%
  filter(
    !is.na(numOocytes)
  )%>%
  scatterPlot_general(
    xVar = dosage,
    xLab = "dosage (mg/kg)",
    yVar = numOocytes,
    yLab = "# of oocytes",
    fillVar = dosage,
    fillLimits = c("0", "2"),
    fillValues = c("white", "black"),
    # lineColorVar = dosage,
    # lineColorLimits = c("black", "black"),
    textSize = 16,
    dotSize = 3,
    hideXAxisLab = FALSE
  ) +
  scale_y_continuous(
    breaks = c(0, 2, 4, 6, 8)
  )

BD_oocytes_plot
```
```{r}
nutellaCortPlot <- BD_cort4 %>%
  filter(
    Sac_date == date_parse("2022-05-27")
  ) %>%
  cortPlot(
    pointSize = 3,
    fontSize = 16,
    plotMean = FALSE, # we don't have enough data yet for mean/se to be helpful
    plotSE = FALSE,
    groupVar = dosage, # group by the dosage; this is why it needs to be a factor
    xBreaks = c(0, 0.5, 1, 3, 5), # set the axis ticks at these values
    xLabels = waiver(), # label the axis with the actual time values
    lineTypeGuide = "",
    positionDodge = 0.2, #this controls the spread of the data visually
    zoom_y = TRUE,
    ymax = 500,
    ymin = 0
  ) +
  # facet_wrap(
  #   ~ateAllNutella # this splits the graph by those that did or did not each Nutella
  # ) +
  labs(
    x = "time since 1st administration (h)" # add a title to the x axis
  ) + 
  theme(
    legend.position = "top"
  )  + 
  dosageFillShape()

nutellaCortPlot
```

```{r}
ALPSCortPlot <- BD_cortALPS %>%
  cortPlot(
    pointSize = 3,
    fontSize = 16,
    plotMean = FALSE, # we don't have enough data yet for mean/se to be helpful
    plotSE = FALSE,
    groupVar = adultTrt, # group by the dosage; this is why it needs to be a factor
    xBreaks = c(0, 0.5, 1, 3, 5), # set the axis ticks at these values
    xLabels = waiver(), # label the axis with the actual time values
    lineTypeGuide = "",
    positionDodge = 0.2, #this controls the spread of the data visually
    zoom_y = TRUE,
    ymax = 500,
    ymin = 0
  ) +
  # facet_wrap(
  #   ~ateAllNutella # this splits the graph by those that did or did not each Nutella
  # ) +
  labs(
    x = "time since 1st administration (h)" # add a title to the x axis
  ) + 
  theme(
    legend.position = "top"
  )  + 
  scale_color_manual(
    "treatment", 
    values = c("ALPS"="black")
  )+
  scale_fill_manual(
    "treatment", 
    values = c("ALPS"="black")
  )+
  scale_shape_manual(
    "treatment", 
    values = c("ALPS"=23)
  )

ALPSCortPlot
```

```{r}
BD_comboNutALPS <- rbind(
  BD_cortALPS %>%
    mutate(
      atePrevNutella = NA,
      ateNutella = NA,
      cortNutTrt = adultTrt
    ), 
  BD_cort4 %>% 
    filter(Sac_date == date_parse("2022-05-27")) %>%
    mutate(
      cortNutTrt = dosage
    )
)
BD_comboNutALPS %>%
  cortPlot(
    pointSize = 3,
    fontSize = 16,
    plotMean = FALSE, # we don't have enough data yet for mean/se to be helpful
    plotSE = FALSE,
    groupVar = cortNutTrt, # group by the dosage; this is why it needs to be a factor
    xBreaks = c(0, 0.5, 1, 3, 5), # set the axis ticks at these values
    xLabels = waiver(), # label the axis with the actual time values
    lineTypeGuide = "",
    positionDodge = 0.2, #this controls the spread of the data visually
    zoom_y = TRUE,
    ymax = 1000,
    ymin = 0
  ) +
  # facet_wrap(
  #   ~ateAllNutella # this splits the graph by those that did or did not each Nutella
  # ) +
  labs(
    x = "time since 1st administration (h)" # add a title to the x axis
  ) + 
  theme(
    legend.position = "top"
  )  +
  scale_color_manual(
    "treatment",
    labels = c(
      "ALPS" = "ALPS",
      "0" = "0mg/kg",
      "2" = "2mg/kg"
    ),
    values = c(
      "ALPS"="black",
      "0" = "black",
      "2" = "black"
      )
  )+
  scale_fill_manual(
    "treatment",
    labels = c(
      "ALPS" = "ALPS",
      "0" = "0mg/kg",
      "2" = "2mg/kg"
    ),
    values = c(
      "ALPS"="grey80",
      "0" = "white",
      "2" = "black"
      )
  )+
  scale_shape_manual(
    "treatment",
    labels = c(
      "ALPS" = "ALPS",
      "0" = "0mg/kg",
      "2" = "2mg/kg"
    ),
    values = c(
      "ALPS"=23,
      "0" = 21,
      "2" = 21
      )
  ) + scale_linetype_manual(
    "treatment",
    labels = c(
      "ALPS" = "ALPS",
      "0" = "0mg/kg",
      "2" = "2mg/kg"
    ),
    values = c(
      "ALPS"="dotted",
      "0" = "solid",
      "2" = "solid"
    )
  )


```


```{r}
BD_cort %>%
  filter(
    time %in% c(0, 5)
    , is.na(exclude) | exclude == FALSE
  ) %>%
  cortPlot(
    pointSize = 3,
    fontSize = 16,
    groupVar = dosage, # group by the dosage; this is why it needs to be a factor
    lineTypeGuide = c("solid", "dotted"),
    positionDodge = 0.2, #this controls the spread of the data visually
    zoom_y = TRUE,
    ymax = 500,
    ymin = 0
  ) +
  facet_wrap(
    ~ dosage,
    labeller = labeller(dosage = c("0" = "0mg/kg", "2" = "2mg/kg"))
  ) +
  # labs(
  #   x = "time since 1st administration (h)" # add a title to the x axis
  # ) + 
  theme(
    legend.position = "none"
  )  + 
  dosageFillShape()
```

```{r}
BD_cort %>%
  filter(
    time %in% c(0, 5)
    , is.na(exclude) | exclude == FALSE
  ) %>%
  anova_test(
    dv = cort,
    between = dosage,
    within = time,
    wid = mouseID
  ) %>%
  formatAnova()

BD_cort %>%
  filter(
    time %in% c(0, 5)
    , is.na(exclude) | exclude == FALSE
  ) %>%
  group_by(
    dosage,
    time
  ) %>%
  meanSummary(cort)
```


```{r}
cortAdmin_timeLHPeak <- BD_sampling %>% makeFactors(dosage) %>% filter(trust == TRUE, !is.na(timeAtMax)) %>%
  scatterPlot_general(
    xVar = dosage,
    xLab = "dosage (mg/kg)"
    , yVar = timeAtMax
    , yLab = "time at max LH\n(hr relative to lights out)"
    , fillVar = dosage
    , fillLimits = c(0, 2)
    , fillValues = c("white", "black")
    , textSize = 16
    , dotSize = 3
    # , jitterWidth = 0.3
    , zoom_y = TRUE
    , ymin = 4.5
    , ymax = 10
  ) + scale_x_discrete(
    labels = c("0" = "0 mg/kg", "2" = "2 mg/kg")
  ) + scale_y_continuous(
    breaks = c(5, 5.5, 6.5, 7.5, 8.5, 9.5),
    labels = c(-2.5, -2, -1, 0, 1, 2)
  )

flexSave(
  "timeLHPeak",
  "cortAdmin",
  cortAdmin_timeLHPeak
  , "png"
  , width = 11
  , height = 5.5
)
```

```{r}
cortAdmin_LHPeak <- BD_sampling %>% makeFactors(dosage) %>% filter(trust == TRUE, !is.na(maxLH)) %>%
  scatterPlot_general(
    xVar = dosage,
    xLab = "dosage (mg/kg)"
    , yVar = maxLH
    , yLab = "peak LH (ng/mL)"
    , fillVar = dosage
    , fillLimits = c(0, 2)
    , fillValues = c("white", "black")
    , textSize = 16
    , dotSize = 3
    # , jitterWidth = 0.3
    # , zoom_y = TRUE
    # , ymin = 4.5
    # , ymax = 10
  ) + scale_x_discrete(
    labels = c("0" = "0 mg/kg", "2" = "2 mg/kg")
  )

cortAdmin_LHPeak

flexSave(
  "LHPeak",
  "cortAdmin",
  cortAdmin_LHPeak
  , "png"
  , width = 11
  , height = 5.5
)

BD_sampling %>%
  makeFactors(dosage) %>%
  filter(
    trust == TRUE
  ) %>%
  propSurgedPlot(
    xVar = dosage,
    fontSize = 16
  )
```

