---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r include=FALSE}
# If can't find it, be sure that the directory is the project directory
# Arrow between notebook and settings gear -> Knit directory
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))
```


```{r}
filePath <- file.path(dataFolder, "cortPlates", "LBN_0006-males-cortPlate.csv")
initialProgress <- processCortEIAtoPercBinding(filePath)

assayPlate <- initialProgress$assayPlate
assayPlate_netOD_meanCV <- initialProgress$assayPlate_netOD_meanCV
assayPlate_indPlusMean_netOD <- initialProgress$assayPlate_indPlusMean_netOD
bufferCtrlOD <- initialProgress$bufferCtrlOD
assayPlate_percBinding <- initialProgress$assayPlate_percBinding

standards <- getCortEIAStandards(assayPlate_percBinding)

modelType <- "4PLC"

finalResults <- processCortEIAtoSamplesEstimates(assayPlate_percBinding, standards, "4PLC")

stdCurve <- finalResults$stdCurve
assayPlate_concEstimates <- finalResults$assayPlate_concEstimates
assayPlate_concEstimates_meanCV <- finalResults$assayPlate_concEstimates_meanCV
samplesEst <- finalResults$samplesEst
meanSampleResults <- finalResults$meanSampleResults
```



