---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r include=FALSE}
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))
source(file.path(scriptsFolder, "04-filter-datasets.R"))
```

```{r}
LBN_data
```


# Cohort 10 remaining
```{r}
LBN_data %>%
  filter(
    cohort == 10
    , sex == "F"
    , is.na(Sac_stop_off)
    , is.na(Sac_date)
    , DOB <= (Sys.Date() - 90)
  ) %>%
  createRemainingPPT(
    addToName = "LBN" 
    , includeYesterday = FALSE
    , cyclesDF = Cycles_off_all
    , IDVar = num_ID
    , trtVar = earlyLifeTrt
    )
```
# Cohort 9 remaining
```{r}
LBN_data %>%
  filter(
    cohort == 9
    , sex == "F"
    , is.na(Sac_stop_off)
    , is.na(Sac_date)
    , DOB < (Sys.Date() - 90)
  ) %>%
  createRemainingPPT(
    addToName = "LBN" 
    , includeYesterday = FALSE
    , cyclesDF = cyclesFiltered
    , IDVar = num_ID
    , trtVar = earlyLifeTrt
    )
```

```{r}
LBN_data %>%
  getMouseInfoForSlicing("927")
```


```{r}
View(AcuteStress_off %>%
  filter(
    cohort == 7
  ) %>%
  arrange(
    comboTrt
  ) %>% select(mouseID, comboTrt, Sac_date))
```

```{r}
samplingDF_today <- AcuteStress_off %>%
  filter(
    Sac_date == date_parse("2024-01-25")
    # Sac_date == dateToday
    # cohort == 5
    , sex == "F"
  )
samplingDF_today <- samplingDF_today %>%
  addRegExForSamplingDF(arrangeByLH = TRUE) %>%
  addSamplingImgFilePaths()
samplingDF_today

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = paste(dateToday),
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  samplingDF_today, 
  samplingPPT = samplingPPT, 
  cyclingDF = Cycles_off_all %>%
    filter(
      mouseID %in% samplingDF_today$mouseID
    )
)
print(samplingPPT, target = file.path(reportOutputFolder, "samplingPPTs", paste0("sampling_",
                                                                                 dateToday,
                                                                                 ".pptx")))
```

Cohorts 4 + 6
```{r eval=FALSE, include=FALSE}
samplingDF_ALPS <- AcuteStress_off %>%
  filter(
    sex == "F",
    !is.na(cyclingFolderPath),
    damStrain == "CBA",
    cohort == 4 | cohort == 6
  )

samplingDF_ALPS <- samplingDF_ALPS %>%
  addRegExForSamplingDF() %>%
  addSamplingImgFilePaths()

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = "LBN Cycling Images, Uterine Mass, and LH Values",
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  samplingDF_ALPS, 
  samplingPPT = samplingPPT, 
  cyclingDF = Cycles_off_all %>%
    filter(
      mouseID %in% samplingDF_ALPS$mouseID
    )
)
print(samplingPPT, target = file.path(reportOutputFolder, "samplingPPTs", paste0(
  "LBN_ALPS_samplingImgs", 
  # dateToday, 
  ".pptx")
  )
)
```
Cohort 7
diestrus
```{r eval=FALSE, include=FALSE}
samplingDF_ALPS <- AcuteStress_off %>%
  filter(
    sex == "F",
    !is.na(cyclingFolderPath),
    damStrain == "CBA",
    cohort == 7 | cohort == 8,
    !is.na(Sac_date),
    !is.na(adultTrt),
    Sac_cycle == "diestrus"
  )

samplingDF_ALPS <- samplingDF_ALPS %>%
  addRegExForSamplingDF() %>%
  addSamplingImgFilePaths()

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = "LBN Cycling Images, Uterine Mass, and LH Values",
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  samplingDF_ALPS, 
  samplingPPT = samplingPPT, 
  cyclingDF = Cycles_off_all %>%
    filter(
      mouseID %in% samplingDF_ALPS$mouseID
    )
)
print(samplingPPT, target = file.path(reportOutputFolder, "samplingPPTs", paste0(
  "LBN_0007_8_ALPS_diestrus_samplingImgs", 
  # dateToday, 
  ".pptx")
  )
)
```

proestrus 
```{r eval=FALSE, include=FALSE}
samplingDF_ALPS <- AcuteStress_off %>%
  filter(
    sex == "F",
    !is.na(cyclingFolderPath),
    damStrain == "CBA",
    cohort == 7 | cohort == 8,
    !is.na(Sac_date),
    !is.na(adultTrt),
    Sac_cycle == "proestrus"
  )

samplingDF_ALPS <- samplingDF_ALPS %>%
  addRegExForSamplingDF() %>%
  addSamplingImgFilePaths()

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = "LBN Cycling Images, Uterine Mass, and LH Values",
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  samplingDF_ALPS, 
  samplingPPT = samplingPPT, 
  cyclingDF = Cycles_off_all %>%
    filter(
      mouseID %in% samplingDF_ALPS$mouseID
    )
)
print(samplingPPT, target = file.path(reportOutputFolder, "samplingPPTs", paste0(
  "LBN_0007_ALPS_proestrus_samplingImgs", 
  # dateToday, 
  ".pptx")
  )
)
```

Full Presentation by Cycle Stage - All CBAs
```{r eval=FALSE, include=FALSE}
samplingDF_ALPS <- AcuteStress_off %>%
  filter(
    sex == "F",
    !is.na(cyclingFolderPath),
    damStrain == "CBA",
    cohort != 2,
    # cohort == 4 | cohort == 5 | cohort == 6
  ) 
samplingDF_ALPS

samplingDF_ALPS <- samplingDF_ALPS %>%
  addRegExForSamplingDF(arrangeByCycle = TRUE, arrangeByTrt = TRUE, arrangeByLH = TRUE) %>%
  addSamplingImgFilePaths()

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = "LBN Cycling Images, Uterine Mass, and LH Values",
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  samplingDF_ALPS %>% 
    filter(
      !(is.na(Sac_cycle)),
      !is.na(ReproTract_mass)
    ) %>%
    mutate(
      hitCycle = ifelse(
        Sac_cycle == "proestrus",
        ifelse(
          ReproTract_mass >= 125,
          TRUE,
          FALSE
        ),
        ifelse(
          Sac_cycle == "diestrus",
          ifelse(
            ReproTract_mass <=100,
            TRUE,
            FALSE
          ),
          NA
        )
      )
    ) %>%
    arrange(-hitCycle, Sac_cycle, comboTrt, maxLH, ReproTract_mass), 
  samplingPPT = samplingPPT, 
  cyclingDF = Cycles_off_all %>%
    filter(
      mouseID %in% samplingDF_ALPS$mouseID
    )
)
print(samplingPPT, target = file.path(reportOutputFolder, "samplingPPTs", paste0(
  "LBN_ALPS_samplingImgs_byStage", 
  # dateToday, 
  ".pptx")
  )
)
```

# Remaining Today
```{r eval=FALSE, include=FALSE}
remainingDF_today <- LBN_data %>%
  filter(
    sex == "F",
    cohort == 7 | cohort == 8,
    # litterNum == 2,
    is.na(Sac_date),
    is.na(Sac_stop_off)
  ) %>%
  mutate(
    Sac_date = dateToday
  ) %>%
  calcAgeInDays() %>%
  combineStress()

remainingDF_today <- remainingDF_today %>%
  addRegExForSamplingDF() %>%
  addSamplingImgFilePaths()

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = paste("Mice remaining on", dateToday),
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  remainingDF_today, 
  samplingPPT = samplingPPT, 
  cyclingDF = Cycles_off_all %>%
    filter(
      mouseID %in% remainingDF_today$mouseID
    )
)

# Cycles_off_all %>% 
#   filter(mouseID %in% remainingDF_today$mouseID) %>%
#   makeCyclesLong() %>%
#   addPNDForCyles() %>%
#   filter(
#     mouseID == "701"
#   )

# remainingDF_today

print(samplingPPT, target = file.path(reportOutputFolder, "remainingPPTs", paste0("remaining_", dateToday, ".pptx")))
```

Cohort 1 CBAs
```{r eval=FALSE, include=FALSE}
cohort1ALPSDF <- AcuteStress_off %>%
  filter(
    sex == "F",
    cohort == 1,
    damStrain == "CBA"
  )

cohort1ALPSDF <- cohort1ALPSDF %>%
  addRegExForSamplingDF() %>%
  addSamplingImgFilePaths()

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = "LBN_0001 Offspring of CBA dams",
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  cohort1ALPSDF, 
  samplingPPT = samplingPPT, 
  cyclingDF = Cycles_off_all %>%
    filter(
      mouseID %in% cohort1ALPSDF$mouseID
    )
)

cohort1ALPSDF

# print(samplingPPT, target = file.path(reportOutputFolder, "samplingPPTs", paste0("LBN_0001-sampling", ".pptx")))
```
