---
title: "R Notebook"
output: html_notebook
---

```{r}
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "summer2024", "02-sagittalGABA_stressAVPV-get-datasets.R"))
```

```{r}
acuteStress_s24 %>%
  filter(
    ReproTract_mass > 90
  )
```


```{r}
cycles_s24
```


```{r}
s24_data %>%
  filter(
    sex == "F"
    , is.na(Sac_date)
    , DOB <= (Sys.Date() - 70)
  ) %>%
  createRemainingPPT(
    addToName = "s24" 
    , includeYesterday = FALSE
    , cyclesDF = cycles_s24
    , IDVar = cycleID
    , trtVar = adultTrt
    )
```


```{r}
s24_data %>%
  getMouseInfoForSlicing("K454")
```


```{r}
samplingDF <- s24_data %>%
  filter(
    !is.na(Sac_date)
  ) %>%
  calcAgeInDays() %>%
  mutate(
    earlyLifeTrt = NA
    , comboTrt = NA
    , num_ID = cycleID
  ) %>%
  addRegExForSamplingDF(numIDVar = cycleID) %>%
  addSamplingImgFilePaths()

samplingPPT <- read_pptx("./samplingSlideTemplate.pptx")
samplingPPT <- add_slide(samplingPPT, layout = "Title Slide")
samplingPPT <- ph_with(
  samplingPPT,
  value = "Cycling Images, Uterine Mass, and LH Values",
  location = ph_location_label("Title 1")
)
addSamplingSlidesFromDF(
  samplingDF, 
  samplingPPT = samplingPPT, 
  cyclingDF = cycles_s24 %>%
    mutate(
      earlyLifeTrt = NA
      , comboTrt = NA
    ) %>%
    filter(
      mouseID %in% samplingDF$mouseID
    )
)
print(samplingPPT, target = file.path(reportOutputFolder, "samplingPPTs", paste0(
  "summer2024_proestrus_samplingImgs",
  ".pptx")
  )
)
```

# Firing and plots


```{r}
AVPVfiring_s24 <- AVPVfiring_s24 %>%
  left_join(
    acuteStress_s24
    , by = "mouseID"
  )
```

```{r}
AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
    , !is.na(frequency)
  ) %>%
  countMiceAndLitters(
    groupingVars = expr(adultTrt)
  )
```

```{r}
AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
    , !is.na(frequency)
  ) %>%
  countMiceAndLitters(
    groupingVars = expr(adultTrt)
  )
```



```{r}
set_sum_contrasts()
set_null_device("png")
```

## Frequency

### LMM
```{r}
freq_lmm <- mixed(
  frequency ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
  )
  , method = "KR"
)

freq_lmm

freq_lmm_EMM <- emmeans(
  freq_lmm$full_model
  , "adultTrt"
)

freq_lmm_EMM

freq_lmm_errors <- freq_lmm %>%
  getErrorDF_LMM("adultTrt")

freq_lmm_errors
```
### Plot

```{r}
freqPlot_pro <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = frequency
    , yLab = "frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
  ) +
   plotError_LMM (
    freq_lmm_errors
    , xVar = adultTrt
  )

freqPlot_pro

flexSave(
  "freq"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = freqPlot_pro
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Freq by time
```{r}
freq_byTimePlot <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
  ) %>%
  scatterPlot_general(
    xVar = recHr
    , xLab = "hr since lights on"
    , yVar = frequency
    , yLab = "frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("CON" = "white", "ALPS" = "black")
    , addMean = FALSE
    , addSE = FALSE
    , hideXAxisLab = FALSE
  ) +
  geom_smooth(
    method = "lm", se = FALSE
    , aes(
      color = adultTrt
    )
  ) +
  scale_color_manual("treatment", values = c( "grey80", "black")) +
  theme(
    legend.position = c(0.1, 1)
  )

freq_byTimePlot

flexSave(
  "freq_byTime"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = freq_byTimePlot
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Frequency

### LMM
```{r}
freq_limitedTime_lmm <- mixed(
  frequency ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
    , recHr <= 15
  )
  , method = "KR"
)

freq_limitedTime_lmm

freq_limitedTime_lmm_EMM <- emmeans(
  freq_limitedTime_lmm$full_model
  , "adultTrt"
)

freq_limitedTime_lmm_EMM

freq_limitedTime_lmm_errors <- freq_limitedTime_lmm %>%
  getErrorDF_LMM("adultTrt")

freq_limitedTime_lmm_errors
```

### Plot

```{r}
freqPlot_pro_limitedTime <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
    , recHr <= 15
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = frequency
    , yLab = "frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
    , zoom_y = TRUE
    , ymin = 0
    , ymax = 10
  ) +
   plotError_LMM (
    freq_limitedTime_lmm_errors
    , xVar = adultTrt
  )

freqPlot_pro_limitedTime

flexSave(
  "freq_toZT15"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = freqPlot_pro_limitedTime
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Burst Frequency

### LMM
```{r}
burstFreq_lmm <- mixed(
  burstFreq ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
  )
  , method = "KR"
)

burstFreq_lmm

burstFreq_lmm_EMM <- emmeans(
  burstFreq_lmm$full_model
  , "adultTrt"
)

burstFreq_lmm_EMM

burstFreq_lmm_errors <- burstFreq_lmm %>%
  getErrorDF_LMM("adultTrt")

burstFreq_lmm_errors
```
### Plot

```{r}
burstFreqPlot_pro <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = burstFreq
    , yLab = "burst frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
  ) +
   plotError_LMM (
    burstFreq_lmm_errors
    , xVar = adultTrt
  )

burstFreqPlot_pro

flexSave(
  "burstFreq"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = burstFreqPlot_pro
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Single spike Frequency

### LMM
```{r}
singleSpikeFreq_lmm <- mixed(
  singleSpikeFreq ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
  )
  , method = "KR"
)

singleSpikeFreq_lmm

singleSpikeFreq_lmm_EMM <- emmeans(
  singleSpikeFreq_lmm$full_model
  , "adultTrt"
)

singleSpikeFreq_lmm_EMM

singleSpikeFreq_lmm_errors <- singleSpikeFreq_lmm %>%
  getErrorDF_LMM("adultTrt")

singleSpikeFreq_lmm_errors
```
### Plot

```{r}
singleSpikeFreqPlot_pro <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass > 90
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = singleSpikeFreq
    , yLab = "single spike frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
  ) +
   plotError_LMM (
    singleSpikeFreq_lmm_errors
    , xVar = adultTrt
  )

singleSpikeFreqPlot_pro

flexSave(
  "singleSpikeFreq"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = singleSpikeFreqPlot_pro
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Frequency - estrus

### LMM
```{r}
freq_lmm_estrus <- mixed(
  frequency ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  )
  , method = "KR"
)

freq_lmm_estrus

freq_lmm_estrus_EMM <- emmeans(
  freq_lmm_estrus$full_model
  , "adultTrt"
)

freq_lmm_estrus_EMM

freq_lmm_estrus_errors <- freq_lmm_estrus %>%
  getErrorDF_LMM("adultTrt")

freq_lmm_estrus_errors
```
### Plot

```{r}
freqPlot_estrus <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = frequency
    , yLab = "frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
    , zoom_y = TRUE
    , ymin = 0
    , ymax = 10
  ) +
   plotError_LMM (
    freq_lmm_estrus_errors
    , xVar = adultTrt
  )

freqPlot_estrus

flexSave(
  "freq_estrus"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = freqPlot_estrus
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Freq by time
```{r}
freq_byTimePlot_estrus <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  ) %>%
  scatterPlot_general(
    xVar = recHr
    , xLab = "hr since lights on"
    , yVar = frequency
    , yLab = "frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("CON" = "white", "ALPS" = "black")
    , addMean = FALSE
    , addSE = FALSE
    , hideXAxisLab = FALSE
  ) +
  geom_smooth(
    method = "lm", se = FALSE
    , aes(
      color = adultTrt
    )
  ) +
  scale_color_manual("treatment", values = c( "grey80", "black")) +
  theme(
    legend.position = c(0.1, 1)
  )

freq_byTimePlot_estrus

flexSave(
  "freq_byTime_estrus"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = freq_byTimePlot_estrus
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Frequency

### LMM
```{r}
freq_estrus_limitedTime_lmm <- mixed(
  frequency ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
    , recHr <= 15
  )
  , method = "KR"
)

freq_estrus_limitedTime_lmm

freq_estrus_limitedTime_lmm_EMM <- emmeans(
  freq_estrus_limitedTime_lmm$full_model
  , "adultTrt"
)

freq_estrus_limitedTime_lmm_EMM

freq_estrus_limitedTime_lmm_errors <- freq_estrus_limitedTime_lmm %>%
  getErrorDF_LMM("adultTrt")

freq_estrus_limitedTime_lmm_errors
```

### Plot

```{r}
freqPlot_estrus_limitedTime <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
    , recHr <= 15
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = frequency
    , yLab = "frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
    , zoom_y = TRUE
    , ymin = 0
    , ymax = 10
  ) +
   plotError_LMM (
    freq_estrus_limitedTime_lmm_errors
    , xVar = adultTrt
  )

freqPlot_estrus_limitedTime

flexSave(
  "freq_toZT15_estrus"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = freqPlot_estrus_limitedTime
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Burst Frequency

### LMM
```{r}
burstFreq_estrus_lmm <- mixed(
  burstFreq ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  )
  , method = "KR"
)

burstFreq_estrus_lmm

burstFreq_estrus_lmm_EMM <- emmeans(
  burstFreq_estrus_lmm$full_model
  , "adultTrt"
)

burstFreq_estrus_lmm_EMM

burstFreq_estrus_lmm_errors <- burstFreq_estrus_lmm %>%
  getErrorDF_LMM("adultTrt")

burstFreq_estrus_lmm_errors
```
### Plot

```{r}
burstFreqPlot_estrus <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = burstFreq
    , yLab = "burst frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
  ) +
   plotError_LMM (
    burstFreq_estrus_lmm_errors
    , xVar = adultTrt
  )

burstFreqPlot_estrus

flexSave(
  "burstFreq_estrus"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = burstFreqPlot_estrus
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```

## Single spike Frequency

### LMM
```{r}
singleSpikeFreq_lmm_estrus <- mixed(
  singleSpikeFreq ~ adultTrt + (1|mouseID)
  , data = AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  )
  , method = "KR"
)

singleSpikeFreq_lmm_estrus

singleSpikeFreq_lmm_estrus_EMM <- emmeans(
  singleSpikeFreq_lmm_estrus$full_model
  , "adultTrt"
)

singleSpikeFreq_lmm_estrus_EMM

singleSpikeFreq_lmm_estrus_errors <- singleSpikeFreq_lmm_estrus %>%
  getErrorDF_LMM("adultTrt")

singleSpikeFreq_lmm_estrus_errors
```
### Plot

```{r}
singleSpikeFreqPlot_estrus <- AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = singleSpikeFreq
    , yLab = "single spike frequency (Hz)"
    , fillVar = adultTrt
    , fillValues = c("white", "black")
    , addMean = FALSE
    , addSE = FALSE
  ) +
   plotError_LMM (
    singleSpikeFreq_lmm_estrus_errors
    , xVar = adultTrt
  )

singleSpikeFreqPlot_estrus

flexSave(
  "singleSpikeFreq_estrus"
  , thisFilePrefix = "AGG_AVPV_"
  ,plot = singleSpikeFreqPlot_estrus
  , fileType = "png"
  , width = 11.5
  , height = 4.76
)
```


```{r}
AVPVfiring_s24 %>%
  filter(
    ReproTract_mass <= 90
  ) %>%
  scatterPlot_general(
    xVar = adultTrt
    , xLab = "treatment"
    , yVar = frequency
    , yLab = "frequency (Hz)"
  )
```



```{r}
AVPVfiring_s24 %>%
  select(
    cellID, adultTrt, ReproTract_mass
  ) %>%
  rowwise() %>%
  mutate(
    group = ifelse(
      adultTrt == "CON" && ReproTract_mass > 90
      , "pro-CON"
      , ifelse(
        adultTrt == "CON" && ReproTract_mass <= 90
        , "estrus-CON"
        , ifelse(
          adultTrt == "ALPS" && ReproTract_mass > 90
          , "pro-ALPS"
          , ifelse(
            adultTrt == "ALPS" && ReproTract_mass <= 90
            , "estrus-ALPS"
          )
        )
      )
    )
  ) %>%
  select(
    cellID, group
  ) %>%
  write.table("clipboard", sep = "\t", row.names = FALSE, col.names = FALSE)
```

```{r}
AVPV_nice <- AVPVfiring_s24 %>%
  mutate(
    recClockTime = timeHr
    , recHrSinceLightsOff = recHr
    , sacHrSinceLightsOff = Sac_hr
    , generation = damCage
  ) %>%
  select(
    cellID
    , mouseID
    , Sac_cycle
    , adultTrt
    , Sac_date
    , recHrSinceLightsOff
    , timeSinceSac
    , AgeInDays
    , duration:singleSpikeFlags
    , sacHrSinceLightsOff
    , DOB
    , generation
    , earTag
    , weanCage
    , strain
    , sex
    , Body_mass_AM
    , Body_mass_sac
    , bodyMass_diff
    , ReproTract_mass
    , ReproTract_mass_perBodyAM_g
    , ReproTract_mass_perBody_g
  ) %>%
  mutate(
    didRec = ifelse(is.na(frequency), FALSE, TRUE)
  ) %>%
  arrange(
    desc(didRec)
  ) %>%
  select(
    -didRec
  )

saveDFsToExcel(
  "cellInfo"
  , "AGG_AVPV_ALPS_"
  , cellInfo = AVPV_nice
)
```


