---
title: "AGG Comittee Meeting 2022-11-01"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
# options(digits=3)
```

```{r eval=FALSE, include=FALSE}
source("./01-scripts/01-set-up.R")
source(file.path(scriptsFolder, "02-get-datasets.R"))
source("./01-scripts/04-filter-datasets.R")
source("./01-scripts/06-run-LBN-stats.R")
source("./01-scripts/05-make-LBN-plots-modelError-manuscript.R")
```

```{r}
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
```

# Set-up
```{r}
figureNum <- 1

pptBaseName <- makeBaseNameFunc("")

plotFolder <- file.path(plotOutputFolder, "2023-10-19")

imgType <-"png"

exportImg <- exportImg_forPurposeFunc(
  imgType = imgType
  , figNumFunc = pptBaseName
  , plotFolder = plotFolder
  , compType = currentCompType
)

exportFullPPTSlide <- function(
    plot = last_plot()
    , baseName = fileBaseName
    , figNum = figureNum
    , width = 11.5
    , height = 5
){
  exportImg(
    plot = plot
    , fileBaseName = baseName
    , figNum = figNum
    , units = "in"
    , width = width
    , height = height
  )
}

exportHalfPPTSlide <- function(
    plot = last_plot()
    , baseName = fileBaseName
    , figNum = figureNum
){
  exportImg(
    plot = plot
    , fileBaseName = baseName
    , figNum = figNum
    , units = "in"
    , width = 5.67
    , height = 5
  )
}

exportThirdPPTSlide <- function(
    plot = last_plot()
    , baseName = fileBaseName
    , figNum = figureNum
){
  exportImg(
    plot = plot
    , fileBaseName = baseName
    , figNum = figNum
    , units = "in"
    , width = 3.6
    , height = 5
  )
}

exportQuarterPPTSlide <- function(
    plot = last_plot()
    , baseName = fileBaseName
    , figNum = figureNum
){
  exportImg(
    plot = plot
    , fileBaseName = baseName
    , figNum = figNum
    , units = "in"
    , width = 3.2
    , height = 5
  )
}

editableImgs <- TRUE
pptAddOneGraph <- function(
    title = slideTitle
    , plot = last_plot()
    , officer_ppt = ppt
){
  officer_ppt <- addSlide_oneGraph(
    officer_ppt, 
    title, 
    plot, 
    makeEditable = editableImgs
  )
  return(officer_ppt)
}

pptAddOneTable <- function(
    table
    , title = slideTitle
    , officer_ppt = ppt
    , dontFormat = TRUE
){
  officer_ppt <- addSlide_oneTable(
    officer_ppt, 
    title, 
    table, 
    dontFormat = dontFormat
  )
  return(officer_ppt)
}

pptUneditAddOneGraph <- function(
    title = slideTitle
    , plot = last_plot()
    , officer_ppt = ppt
){
  officer_ppt <- addSlide_oneGraph(
    officer_ppt, 
    title, 
    plot, 
    makeEditable = FALSE
  )
  return(officer_ppt)
}

pptAddTwoGraphs <- function(
    plot1
    , plot2
    , title = slideTitle
    , officer_ppt = ppt
){
  officer_ppt <- addSlide_twoGraph(
    officer_ppt, 
    title, 
    plot1, 
    plot2,
    makeEditable = editableImgs
  )
  return(officer_ppt)
}

pptAddTwoGraphsMoreLeft <- function(
    plot1
    , plot2
    , title = slideTitle
    , officer_ppt = ppt
){
  officer_ppt <- addSlide_twoGraphMoreLeft(
    officer_ppt, 
    title, 
    plot1, 
    plot2,
    makeEditable = editableImgs
  )
  return(officer_ppt)
}

pptAddGraphTable <- function(
    plot
    , table
    , title = slideTitle
    , officer_ppt = ppt
    , dontFormat = TRUE
){
  officer_ppt <- addSlide_graphTable(
    officer_ppt, 
    title, 
    plot, 
    table,
    makeEditable = editableImgs
    , dontFormat = dontFormat
    , textSize = textSize
  )
  return(officer_ppt)
}

pptAddFourGraphs <- function(
    plot1
    , plot2
    , plot3
    , plot4
    , title = slideTitle
    , officer_ppt = ppt
){
  officer_ppt <- addSlide_fourGraph(
    officer_ppt, 
    title, 
    plot1, 
    plot2, 
    plot3,
    plot4,
    makeEditable = editableImgs
    )
  return(officer_ppt)
}

pptAddThreeGraphs <- function(
    plot1
    , plot2
    , plot3
    , title = slideTitle
    , officer_ppt = ppt
){
  officer_ppt <- addSlide_threeGraph(
    officer_ppt, 
    title, 
    plot1, 
    plot2, 
    plot3,
    makeEditable = editableImgs
    )
  return(officer_ppt)
}

pptAddStats <- function(
    statsText
    , officer_ppt = ppt
){
  officer_ppt <- addStatsToBottom(
    officer_ppt,
    statsText
  )
}

pptAddTwoStats <- function(
    statsText1
    , statsText2
    , officer_ppt = ppt
){
  officer_ppt <- addTwoStatsToGraphs(
    officer_ppt,
    statsText1,
    statsText2
  )
}

pptAddSectionHead <- function(
    title = slideTitle
    , officer_ppt = ppt
){
  officer_ppt <- addSlide_sectionHead(
    officer_ppt
    , title
  )
}



```

```{r}
# make powerpoint and title slide
ppt <- read_pptx("genericPPT.pptx")
ppt <- add_slide(ppt, layout = "Title Slide")

# layout_properties(ppt, layout="Title Slide")

subText <- "Amanda Gibson\nData Update\nSept 5, 2023"
ppt <- ph_with(
  ppt,
  value = subText,
  location = ph_location_label("Subtitle 2")
)


# Run this function to save the PPT file to the disk
# On windows, don't run if the PPT file is open
savePPT <- makeSavePPTFunc(
  presPPT = ppt
  , presFolder = plotFolder
  , presFileName = "AGG_LBN_update"
  , addDate = TRUE
)
```


# Dams - number of exits

```{r}
plot_grid(
  figDams_exits
  , figDams_meanExits
  , rel_widths = c(3, 1)
  , align = c("hv")
)

fileBaseName <- "damBehavior"
slideTitle <- "LBN dams had more exits from the nest than STD dams"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  coef(summary(numExits_nb.GLMM)) %>%
    as.data.frame() %>%
    rownames_to_column("effect"),
  dontFormat = FALSE
)
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  numExits_nb.GLMM_jointTest,
  dontFormat = FALSE
)
```

# Dams - % off nest

```{r}
plot_grid(
  figDams_offNest
  , figDams_meanOffNest
  , rel_widths = c(3, 1)
  , align = c("hv")
)

fileBaseName <- "damBehavior_percOff"
slideTitle <- "LBN did not alter the percent of time spent off the nest"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  percOffNest_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

# Dam corticosterone

```{r}
figDamsD

fileBaseName <- "damCort"
slideTitle <- "PND11 corticosterone was not different after LBN"
exportHalfPPTSlide()
ppt <- pptAddTwoGraphs(
  figDamsD
  , figDamsD
)

ppt <- addStatsToBottom(ppt, paste0(
  "t = "
  , round(damCort_t.Test$statistic[[1]], 3)
  , ", p = "
  , round(damCort_t.Test$p.value[[1]], 3)
  )
)
```

# Dam mass

```{r}
figDams_mass

fileBaseName <- "damMass"
slideTitle <- "LBN dams have a higher body mass than STD dams"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_twoTables(
  ppt,
  slideTitle,
  damMass_lmm$anova_table %>% as.data.frame(),
  damMass_lmm_EMM.earlyLifeTrt.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

# Offspring mass 

```{r}
figOffA

fileBaseName <- "offMass"

exportFullPPTSlide()
slideTitle <- "Offspring mass"
ppt <- pptAddOneGraph()
```

# Offspring maturation

```{r}
figOffAge_model

fileBaseName <- "matAge"

exportFullPPTSlide()
slideTitle <- "LBN does not alter age for external markers of puberty"
ppt <- pptAddOneGraph()
```
```{r}
figOffMass_model

fileBaseName <- "matMass"

exportFullPPTSlide()
slideTitle <- "LBN does not alter mass at external markers of puberty"
ppt <- pptAddOneGraph()
```

```{r}
slideTitle <- "Vaginal opening"
ppt <- addSlide_twoTables(
  ppt,
  slideTitle,
  VO_age_lmm %>% formatMixedLMM_ppt(),
  VO_mass_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```
```{r}
slideTitle <- "First Estrus"
ppt <- addSlide_twoTables(
  ppt,
  slideTitle,
  Estrus_age_lmm %>% formatMixedLMM_ppt(),
  Estrus_mass_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```
```{r}
slideTitle <- "Preputial Separation"
ppt <- addSlide_twoTables(
  ppt,
  slideTitle,
  PreputialSep_age_lmm %>% formatMixedLMM_ppt(),
  PreputialSep_mass_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

# AGD

```{r}
plot_grid(
  figOff_femaleAGD
  , figOff_maleAGD
  , align = "hv"
  , axis = "tblr"
)

fileBaseName <- "matAGD"

exportFullPPTSlide()
slideTitle <- "LBN does not alter adult AGD"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  AGD_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

# Estrous cycle

```{r}
plot_grid(
  figCycles_numCycles_model
  , figCycles_lengthLog_model
  , figCyclesD
  , ncol = 3
  , align = "h"
  , axis = "bt"
  , rel_widths = c(1, 1, 2)
)

fileBaseName <- "cyclesFeatures"

exportFullPPTSlide()
slideTitle <- "LBN does not alter estrous cyclicity"
ppt <- pptAddOneGraph()
```

```{r}
slideTitle <- "Number of cycles"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  numCycles_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
slideTitle <- "Cycle length"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  lengthCycles_log_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
slideTitle <- "Cycle distribution"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  cycles_ChiSq,
  dontFormat = FALSE
)
```


# Cort

```{r}
figCortLogA

fileBaseName <- "cortMales"

exportFullPPTSlide()
slideTitle <- "LBN does not alter corticosterone response to ALPS in males"
ppt <- pptAddOneGraph()
```

```{r}
figCortLogB

fileBaseName <- "cortDi"

exportFullPPTSlide()
slideTitle <- "LBN does not alter corticosterone response to ALPS in diestrous females"
ppt <- pptAddOneGraph()
```

```{r}
figCortLogC

fileBaseName <- "cortPro"

exportFullPPTSlide()
slideTitle <- "LBN does not alter corticosterone response to ALPS in proestrous females"
ppt <- pptAddOneGraph()
```

```{r}
slideTitle <- "LBN does not alter corticosterone response to ALPS"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  cort_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
slideTitle <- "ALPS increases afternoon serum corticosterone"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  cort_lmm_emm_adultTrtTime.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

```{r}
slideTitle <- "Corticosterone varies with hormone status"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  cort_lmm_emm_hormoneStatusTime.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

```{r}
cortFiltered_M_DiPro %>%
  manuscriptCortPlotFunc(
    fontSize = textSize
    , dotSize = dotSize
    , zoom_y = FALSE
    , plotMean = FALSE
    , plotSE = FALSE
    , pointAlpha = 0.1
    , lineAlpha = 0.1
  )() +
  facet_wrap(
    ~hormoneStatus
  ) +
  cortScale +
 plotError_LMM(
   cort_lmm_emm_hormoneStatusTime %>%
   as_data_frame() %>%
  rename(
    y = response
  ) %>%
  mutate(
    lower = y - SE
    , upper = y + SE
    ,time = ifelse(
      time == 0
      , time - 1.5
      , time + 1.5
    )
  )
  , xVar = time
  , nudgeErrorLine = 0
  , nudgeMeanLine = 0
  , meanBarWidth = 1
  , color = "black"
)


ppt <- pptAddOneGraph()
```



# Body mass - AM

```{r}
figMassFacetA_model

fileBaseName <- "bodyMassAM"

exportFullPPTSlide()
slideTitle <- "There were some differences in body mass between male treatment groups"
ppt <- pptAddOneGraph()
```
```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  bodyMassAM_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
slideTitle <- "Males that went on to receive ALPS were larger than those that received CON"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  bodyMassAM_lmm_emm_adultTrt.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

```{r}
slideTitle <- "LBN males were trending towards being smaller than STD males"
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  bodyMassAM_lmm_emm_earlyLifeTrt.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

# % change body mass

```{r}
figMassFacetB_perc_model

fileBaseName <- "bodyMassPercChange"

exportFullPPTSlide()
slideTitle <- "ALPS mice lost more body mass than CON mice during the paradigm"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  percChangeBodyMass_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  percChangeBodyMass_lmm_emm_adultTrt.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

# Adrenal mass

```{r}
figMassFacetC_model

fileBaseName <- "adrenalMass"

exportFullPPTSlide()
slideTitle <- "Females have larger adrenal glands than males"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  adrenalMass_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  adrenalMass_lmm_emm_hormoneStatus.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

# Seminal vesicle mass

```{r}
figMassFacetD_male_model

fileBaseName <- "seminalVesicleMass"

exportFullPPTSlide()
slideTitle <- "Relative seminal vesicle mass is larger in LBN males"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  seminalVesicle_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  seminalVesicle_lmm_emm_earlyLifeTrt.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

# Uterine mass

```{r}
figMassFacetD_female_model

fileBaseName <- "uterineMass"

exportFullPPTSlide()
slideTitle <- "Proestrus females have larger uteri than diestrus females (... by definition)"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  uterineMass_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  uterineMass_lmm_emm_stage.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

# Testicular mass

```{r}
figMass_testicular_model

fileBaseName <- "testicularMass"

exportFullPPTSlide()
slideTitle <- "ALPS males have a smaller relative testicular mass"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  testicularMass_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  testicularMass_lmm_emm_adultTrt.pairs %>% as.data.frame(),
  dontFormat = FALSE
)
```

# LH results

```{r}
ephys_percSurgedPlot <- surgedDF %>%
  filter(
    is.na(LH_hr7.5) & !is.na(LH_hr5.5)
  ) %>%
  propSurgedPlotCombo_forSBN(
    fontSize = textSize
  )

ephys_percSurgedPlot

fileBaseName <- "percSurgedEphys"

exportFullPPTSlide()
```

```{r}
ephysMice <- surgedDF %>%
  filter(
    is.na(LH_hr7.5) & !is.na(LH_hr5.5)
  )
ephysLH <- LHFilteredPro %>%
  filter(
    mouseID %in% ephysMice$mouseID
    , time > 0
  ) %>%
  plotLHFunc(
    c(1)
    , fontSize = 16
    , dotSize = dotSize
    , addSurgeLine = TRUE
  )()

ephysLH

fileBaseName <- "percSurgedEphys_trace"
exportFullPPTSlide()
```
```{r}
nonEphysMice <- surgedDF %>%
  filter(
    !is.na(LH_hr7.5) & !is.na(LH_hr5.5)
  )
samplingLH <- LHFilteredPro %>%
  filter(
    mouseID %in% nonEphysMice$mouseID
    , time > 0
  ) %>%
  plotLHFunc(
    c(1)
    , fontSize = 16
    , dotSize = dotSize
    , addSurgeLine = TRUE
  )()

samplingLH

```

```{r}
sampling_percSurgedPlot <- surgedDF %>%
  filter(
    !is.na(LH_hr7.5) & !is.na(LH_hr5.5)
  ) %>%
  propSurgedPlotCombo_forSBN(
    fontSize = textSize
  )

sampling_percSurgedPlot
```


```{r}
plot_grid(
  ephysLH + 
    scale_x_continuous(
      breaks = c(5, 5.5)
      , labels = c(-2.5, -2)
    )
  , ephys_percSurgedPlot
  , nrow = 1
  , rel_widths = c(1.5, 1)
)

fileBaseName <- "ephysLHPlots"

exportFullPPTSlide(
  height = 5.75
)

slideTitle <- "With limited sampling for ephys mice, did not detect surge in many LBN mice"
ppt <- pptAddOneGraph()
```
```{r}
plot_grid(
  samplingLH
  , sampling_percSurgedPlot
  , nrow = 1
  , rel_widths = c(1.5, 1)
)

fileBaseName <- "samplingLHPlots"

exportFullPPTSlide(
  height = 5.75
)

slideTitle <- "With full sampling window, 3/5 LBN-ALPS mice still surged"
ppt <- pptAddOneGraph()
```


# GABA PSC Freq

```{r}
figGABAe_model

fileBaseName <- "GABAfreq"

exportFullPPTSlide()
slideTitle <- "Neither LBN nor ALPS altered the frequency of GABA PSCs"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
   coef(summary(numEvents_nb.GLMM)) %>%
    as.data.frame() %>%
    rownames_to_column("effect"),
  dontFormat = FALSE
)
```

# GABA PSC Amp

```{r}
figGABAf_model

fileBaseName <- "GABAamp"

exportFullPPTSlide()
slideTitle <- "Neither LBN nor ALPS altered the amplitude of GABA PSCs"
ppt <- pptAddOneGraph()
```

```{r}
ppt <- addSlide_oneTable(
  ppt,
  slideTitle,
  relAmplitude_lmm %>% formatMixedLMM_ppt(),
  dontFormat = FALSE
)
```

```{r}
GABAlegend <- get_legend(figGABAb_model + theme(legend.position = "top"))

plot_grid(
  GABAlegend
  , plot_grid(
    figGABAa_model +
      theme(
        axis.text.x = element_blank()
      )
    , figGABAb_model+
      theme(
        axis.text.x = element_blank()
      )
    , figGABAc_model+
      theme(
        axis.text.x = element_blank()
      )
    , figGABAd_model+
      theme(
        axis.text.x = element_blank()
      )
    , align = "h"
    , axis = "tb"
    , nrow = 1
  )
  , nrow = 2
  , rel_heights = c(0.1, 1)
)

fileBaseName <- "GABApassives"

exportFullPPTSlide()
slideTitle <- "Neither LBN nor ALPS altered passive properties or recording quality"
ppt <- pptAddOneGraph()
```

```{r}
maleCortAdmin_plotByConsumption

fileBaseName <- "maleCortPlotByConsumption"

slideTitle <- "Serum corticosterone is elevated by corticosterone consumption"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```
```{r}
latterCortAdmin_plotByConsumption

fileBaseName <- "maleCortPlotByConsumption"

slideTitle <- "Serum corticosterone is elevated by corticosterone consumption"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```
```{r}
maleCortAdmin_AMBodyMass

fileBaseName <- "maleCortAdmin_AMBodyMass"

slideTitle <- "AM Body mass"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}
maleCortAdmin_PercChangeBodyMass

fileBaseName <- "maleCortAdmin_PercChangeBodyMass"

slideTitle <- "% Change in Body Mass"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}
maleCortAdmin_TesticularMass

fileBaseName <- "maleCortAdmin_TesticularMass"

slideTitle <- "Testicular mass"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}
maleCortAdmin_SeminalVesicleMass

fileBaseName <- "maleCortAdmin_SeminalVesicleMass"

slideTitle <- "Seminal vesicle mass"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}
maleCortAdmin_AdrenalMass

fileBaseName <- "maleCortAdmin_AdrenalMass"

slideTitle <- "Adrenal mass"
exportFullPPTSlide()
ppt <- pptAddOneGraph()
```

```{r}

```

